server:
  port: 8080

spring:
  application:
    name: rangiffler-gateway

  grpc:
    client:
      channels:
        countries-service:
          address: 127.0.0.1:9090
        userdata-service:
          address: 127.0.0.1:9091
        countries-photos:
          address: 127.0.0.1:9093

  logging:
    file:
      path: ./logs/rangiffler-gateway
    level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.security: INFO
      org.springframework.security.oauth2: INFO
      net.devh.boot.grpc: INFO
      org.springframework.boot.autoconfigure: INFO

  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-gateway:
  base-uri: 'http://127.0.0.1:8080'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8081'
rangiffler-countries:
  base-uri: 'http://127.0.0.1:8082'
rangiffler-photos:
  base-uri: 'http://127.0.0.1:8083'
