server:
  port: 8080

spring:
  application:
    name: rangiffler-gateway

  logging:
    file:
      path: ./logs/rangiffler-gateway
    level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.security: INFO
      org.springframework.security.oauth2: INFO
      net.devh.boot.grpc: INFO
      org.springframework.boot.autoconfigure: INFO

  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

  graphql:
    graphiql:
      enabled: true

    schema:
      introspection:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-gateway:
  base-uri: 'http://127.0.0.1:8080'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8081'
