syntax = "proto3";

package guru.qa.grpc.rangiffler;

import "google/protobuf/empty.proto";
import "google/type/date.proto";

option java_multiple_files = true;
option java_package = "guru.qa.rangiffler.grpc";
option java_outer_classname = "RangifflerUserdataProto";

service RangifflerUserdataService {
    rpc GetUser(UserRequest) returns (UserResponse);
    rpc GetUserWithFriendStatus(UserWithStatusRequest) returns (UserResponse);
    rpc AllUsers(UsersPaginatedRequest) returns (UsersPaginatedResponse);
    rpc UpdateUser(UserUpdateRequest) returns (UserUpdateResponse);
    rpc AllFriendsPaginated(AllFriendsPaginatedRequest) returns (AllFriendsPaginatedResponse);
    rpc AllFriends(AllFriendsRequest) returns (AllFriendsResponse);
    rpc GetIncomeInvitations(InvitationsPaginatedRequest) returns (InvitationsPaginatedResponse);
    rpc GetOutcomeInvitations(InvitationsPaginatedRequest) returns (InvitationsPaginatedResponse);
    rpc CreateFriendshipRequest(FriendshipRequest) returns (FriendshipResponse);
    rpc AcceptFriendshipRequest(FriendshipRequest) returns (FriendshipResponse);
    rpc DeclineFriendshipRequest(FriendshipRequest) returns (FriendshipResponse);
    rpc DeleteFriend(FriendshipRequest) returns (FriendshipResponse);
}

service RangifflerCountriesService {
    rpc GetCountry(CountryRequest) returns (CountryResponse);
    rpc AllCountries(google.protobuf.Empty) returns (CountriesResponse);
    rpc GetCountriesByIds(NeededCountriesRequest) returns (NeededCountriesResponse);
}

service RangifflerPhotosService {
    rpc AddPhoto(PhotoRequest) returns (PhotoResponse);
    rpc UpdatePhoto(PhotoUpdateRequest) returns (PhotoResponse);
    rpc DeletePhoto(PhotoDeleteRequest) returns (PhotoDeleteResponse);
    rpc AddPhotoLike(PhotoLikeRequest) returns (PhotoResponse);
    rpc DeletePhotoLike(PhotoLikeRequest) returns (PhotoResponse);
    rpc GetPhotoWithLikes(PhotoWithLikesRequest) returns (PhotoResponse);
    rpc GetUserFeed(FeedRequest) returns (FeedResponse);
}

message PaginationRequest {
    int32 page = 1;
    int32 size = 2;
}

message PaginationResponse {
    int32 current_page = 1;
    int32 page_size = 2;
    int32 total_pages = 3;
    int64 total_elements = 4;
    bool has_next = 5;
    bool has_previous = 6;
}

message UserUpdateRequest {
    string username = 1;
    optional string firstname = 2;
    optional string surname = 3;
    optional bytes photo = 4;
    optional string country_id = 5;
}

message UserUpdateResponse {
    string id = 1;
    string username = 2;
    optional string firstname = 3;
    optional string surname = 4;
    optional bytes photo = 5;
    optional string country_id = 6;
}

message UserRequest {
    string username = 1;
    optional string id = 2;
}

message UserWithStatusRequest {
    string target_user_id = 1;
    string current_user_id = 2;
}

message UserResponse {
    string id = 1;
    string username = 2;
    string firstname = 3;
    string surname = 4;
    bytes photo = 5;
    FriendStatus friend_status = 6;
    repeated UserResponse friends = 7;
    repeated UserResponse income_invitations = 8;
    repeated UserResponse outcome_invitations = 9;
    string country_id = 10;
}

message UsersPaginatedRequest {
    string exclude_username = 1;
    PaginationRequest pagination_request = 2;
}

message UsersPaginatedResponse {
    repeated UserResponse users = 1;
    PaginationResponse pagination_response = 2;
}

message Friend {
    string id = 1;
    string username = 2;
    string firstname = 3;
    string surname = 4;
    bytes photo = 5;
    string country_id = 6;
    FriendStatus status = 7;
}

message FriendshipRequest {
    string username = 1;
    string target_username = 2;
}

message FriendshipResponse {
    string id = 1;
    string username = 2;
    FriendStatus status = 3;
}

message AllFriendsPaginatedRequest {
    string target_username = 1;
    optional string search_query = 3;
    PaginationRequest pagination_request = 2;
}

message AllFriendsPaginatedResponse {
    repeated Friend friends = 1;
    PaginationResponse pagination_response = 2;
}

message AllFriendsRequest {
    string target_username = 1;
}

message AllFriendsResponse {
    repeated Friend friends = 1;
}

message InvitationsPaginatedRequest {
    string target_username = 1;
    optional string search_query = 2;
    PaginationRequest pagination_request = 3;
}

message InvitationsPaginatedResponse {
    repeated Friend invitations = 1;
    PaginationResponse pagination_response = 2;
}

message CountryRequest {
    string code = 1;
    optional string id = 2;
}

message CountryResponse {
    string id = 1;
    string name = 2;
    string code = 3;
    bytes flag = 4;
}

message NeededCountriesRequest {
    repeated string id = 1;
}

message NeededCountriesResponse {
    repeated CountryResponse countries = 1;
}

message CountryPhoto {
    string name = 1;
    string code = 2;
    bytes flag = 3;
}

message CountryStatistic {
    uint32 count = 1;
    string code = 2;
}

message CountriesResponse {
    repeated CountryResponse countries = 1;
}

message Like {
    string user_id = 1;
}

message PhotoRequest {
    string user_id = 1;
    string country_code = 2;
    string description = 3;
    bytes src = 4;
    optional Like like = 5;
}

message PhotoResponse {
    string id = 1;
    string user_id = 2;
    string description = 4;
    bytes src = 5;
    CountryPhoto country = 3;
    repeated Like likes = 6;
    google.type.Date date_created = 7;
}

message PhotoDeleteResponse {
    string id = 1;
}

message PhotoWithLikesRequest {
    string id = 1;
}

message PhotoDeleteRequest {
    string id = 1;
    string user_id = 2;
}

message PhotoUpdateRequest {
    string id = 1;
    string user_id = 2;
    string description = 4;
    bytes src = 5;
    CountryPhoto country = 3;
}

message PhotoLikeRequest {
    string photo_id = 1;
    Like like = 2;
}

message UserCountryStatistic {
    repeated CountryStatistic countries = 2;
}

message FeedRequest {
    string user_id = 1;
    bool with_friends = 2;
    PaginationRequest pagination_request = 3;
}

message FeedResponse {
    FeedPhotos photos = 1;
    UserCountryStatistic statistic = 2;
}

message FeedPhotos {
    repeated PhotoResponse photos = 1;
    PaginationResponse pagination_response = 2;
}

enum FriendStatus {
    NOT_FRIEND = 0;
    INVITATION_SENT = 1;
    INVITATION_RECEIVED = 2;
    FRIEND = 3;
}