server:
  port: 8083

spring:
  application:
    name: rangiffler-photos

  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

  grpc:
    client:
      default-channel:
        negotiation-type: PLAINTEXT
    server:
      port: 9093
      servlet:
        enabled: false

  logging:
    file:
      path: ./logs/rangiffler-photos
    level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.security: INFO
      org.springframework.security.oauth2: INFO
      org.springframework.boot.autoconfigure: INFO
      org.springframework.grpc: INFO

  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rangiffler-photos

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: 'local'
  grpc:
    client:
      countries-service:
        address: 'http://127.0.0.1:9090'
        negotiationType: PLAINTEXT
      userdata-service:
        address: 'http://127.0.0.1:9091'
        negotiationType: PLAINTEXT
  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/rangiffler-photos'
    username: postgres
    password: secret
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:postgresql://rangiffler-all-db:5432/rangiffler-photos'
    username: postgres
    password: secret