plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.4.4'
}

group = 'guru.qa'
version = 'unspecified'

dependencies {
    implementation project(":rangiffler-grpc-common")
    implementation project(":rangiffler-userdata")
    implementation project(":rangiffler-countries")

    implementation 'org.springframework.boot:spring-boot-starter-web'
}

bootJar {
    enabled = true
}