plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.5'
}

group = 'guru.qa'
version = 'unspecified'

dependencies {
    //GRPC
    api 'org.springframework.grpc:spring-grpc-spring-boot-starter'
    api "com.google.protobuf:protobuf-java-util:${dependencyManagement.importedProperties['protobuf-java.version']}"
    api 'io.grpc:grpc-services'
    //UTIL
    api "org.mapstruct:mapstruct:${project.ext.mapStructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${project.ext.mapStructVersion}"
    annotationProcessor "org.projectlombok:lombok:1.18.38"
    compileOnly "org.projectlombok:lombok:1.18.38"
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${dependencyManagement.importedProperties['protobuf-java.version']}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${dependencyManagement.importedProperties['grpc.version']}"
        }
    }
    generateProtoTasks {
        all().configureEach {
            task ->
                task.plugins {
                    grpc {
                        option 'jakarta_omit'
                        option '@generated=omit'
                    }
                }
        }
    }
}