plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.5'
}

group = 'guru.qa'
version = '1.0.0'

dependencies {
    api "com.google.protobuf:protobuf-java-util:${dependencyManagement.importedProperties['protobuf-java.version']}"
    api 'io.grpc:grpc-services'
    api 'io.grpc:grpc-protobuf'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${dependencyManagement.importedProperties['protobuf-java.version']}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${dependencyManagement.importedProperties['grpc.version']}"
        }
    }
    generateProtoTasks {
        all().configureEach {
            task ->
                task.plugins {
                    grpc {
                        option 'jakarta_omit'
                        option '@generated=omit'
                    }
                }
        }
    }
}