plugins {
    id 'org.springframework.boot' version '3.4.4'
}

group = 'guru.qa'
version = '2.3.0'

dependencies {
    implementation project(':rangiffler-grpc-common')

    //gRPC
    implementation 'org.springframework.grpc:spring-grpc-client-spring-boot-starter'
    //WEB
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation('org.springframework.boot:spring-boot-starter-web-services') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    implementation 'org.springframework.ws:spring-ws-core'
    implementation 'org.springframework.data:spring-data-commons'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    //graphQL
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation "com.tailrocks.graphql:graphql-datetime-spring-boot-starter:${project.ext.springGraphqlDateTimeVersion}"
    //UTIL
    annotationProcessor "org.mapstruct:mapstruct-processor:${project.ext.mapStructVersion}"
    implementation "org.mapstruct:mapstruct:${project.ext.mapStructVersion}"
    annotationProcessor "org.projectlombok:lombok:${project.ext.lombokVersion}"
    compileOnly "org.projectlombok:lombok:${project.ext.lombokVersion}"
    //TEST
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "org.springframework.security:spring-security-test:${project.ext.springSecurityTestVersion}"
}